version: '3.8'

services:
  backend:
    build:
      context: .
      target: backend
    ports:
      - "8000:8000"
    volumes:
      - ./backend/data:/app/backend/data
    environment:
      - TRADER_DATABASE_URL=sqlite:///./data/trading.db
      - TRADER_CORS_ORIGINS=["http://localhost:3000"]
    restart: unless-stopped

  frontend:
    build:
      context: .
      target: frontend
    ports:
      - "3000:3000"
    depends_on:
      - backend
    environment:
      - NEXT_PUBLIC_API_URL=http://localhost:8000
    restart: unless-stopped

volumes:
  trading_data:
